#+STARTUP:indent
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/styles.css"/>
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono|Ubuntu' rel='stylesheet' type='text/css'>
#+HTML_HEAD_EXTRA: <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
#+HTML_HEAD_EXTRA: <script src="js/navbar.js" type="text/javascript"></script>
#+OPTIONS: f:nil num:1 creator:nil timestamp:nil toc:nil html-style:nil

#+TITLE: Homework tasks
#+AUTHOR: A.Stout & S.Fone
#+BEGIN_HTML
  <div class="github-fork-ribbon-wrapper left">
    <div class="github-fork-ribbon">
      <a href="https://github.com/digixc/8-CS-ProblemSolving">Fork me on GitHub</a>
    </div>
  </div>
<div id="stickyribbon">
    <ul>
      <li><a href="1_Lesson.html">Week1</a></li>
      <li><a href="2_Lesson.html">Week2</a></li>
      <li><a href="3_Lesson.html">Week3</a></li>
      <li><a href="4_Lesson.html">Week4</a></li>
      <li><a href="5_Lesson.html">Week5</a></li>
      <li><a href="homework.html">Homework</a></li>

    </ul>
  </div>
#+END_HTML
* COMMENT Use as a template
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:

** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:

** Design It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:

** Build It
:PROPERTIES:
:HTML_CONTAINER_CLASS: build
:END:

** Test It
:PROPERTIES:
:HTML_CONTAINER_CLASS: test
:END:

** Run It
:PROPERTIES:
:HTML_CONTAINER_CLASS: run
:END:

** Document It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:

** Code It
:PROPERTIES:
:HTML_CONTAINER_CLASS: code
:END:

** Program It
:PROPERTIES:
:HTML_CONTAINER_CLASS: program
:END:

** Try It
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:

** Badge It
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:

** Save It
:PROPERTIES:
:HTML_CONTAINER_CLASS: save
:END:

* Homework
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Homework 1 - Terminology Quiz.
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:
Click on following [[https://www.proprofs.com/quiz-school/story.php?title=ict-database-questions][Link]] to take a quiz on Database Terminology, you should aim to get at least 50%.
Then take a snippet of the score and uploaded it onto BourneToLearn.

** Homework 2 - Research Task.
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:

Using the following [[https://www.bbc.com/bitesize/guides/z8yg87h/revision/1][link]] research Databases and answer the following questions.

- What is a flat file database?
- What is a relational database?
- What is a primary key and how is it used?
- What is a foreign key and how does it relate to the primary key?

Your answers should be full sentences using connectives. Try and write a short paragraph for each by discussing the main points, advantages and disadvantages etc.
You need to write a minimum of 200 words in total covering all 4 questions.
	 
** Homework 3 - Referential Integrity Research
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:

In your last lesson, you have learned about how we can link two tables together and should know that every foreign key value has a matching value in the corresponding primary key.

Your Task: (200 words minimum)
1.	Research and explain what referential integrity is?
2.	Why do we need to use referential integrity?
3.	Find several examples of databases using referential integrity (Diagrams can be used to support).



